/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;

/**
 *
 * @author cuent
 */
public class Carnet extends javax.swing.JPanel implements Printable{

    /**
     * Creates new form Carnet
     */
    public Carnet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCarnet = new javax.swing.JPanel();
        lblImagenMascota = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDueño = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMascota = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblHuella = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();

        pCarnet.setBackground(new java.awt.Color(255, 255, 255));
        pCarnet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        pCarnet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagenMascota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pCarnet.add(lblImagenMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 82, 190, 204));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("HUELLA VERDE");
        pCarnet.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Dueño: ");
        pCarnet.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 60, -1));

        lblDueño.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pCarnet.add(lblDueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 190, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("DNI:");
        pCarnet.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 60, -1));

        lblDNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pCarnet.add(lblDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 160, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mascota:");
        pCarnet.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 70, -1));

        lblMascota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pCarnet.add(lblMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 160, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tipo:");
        pCarnet.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 60, -1));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pCarnet.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 160, 20));

        lblSexo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pCarnet.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 160, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Sexo:");
        pCarnet.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 60, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Direccion:");
        pCarnet.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 70, -1));

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pCarnet.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 160, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Telefono:");
        pCarnet.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 70, -1));

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pCarnet.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 160, 20));
        pCarnet.add(lblHuella, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 100, 100));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("CODIGO:");
        pCarnet.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 190, 30));

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pCarnet.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pCarnet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lblCodigo;
    public javax.swing.JLabel lblDNI;
    public javax.swing.JLabel lblDireccion;
    public javax.swing.JLabel lblDueño;
    public javax.swing.JLabel lblHuella;
    public javax.swing.JLabel lblImagenMascota;
    public javax.swing.JLabel lblMascota;
    public javax.swing.JLabel lblSexo;
    public javax.swing.JLabel lblTelefono;
    public javax.swing.JLabel lblTipo;
    public javax.swing.JPanel pCarnet;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if(pageIndex == 0){
            Graphics2D graphics2d=(Graphics2D) graphics;
            graphics2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());
            printAll(graphics2d);
            return PAGE_EXISTS;
        }else{
            return NO_SUCH_PAGE;
        }
    }
    
    
}
