/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author cuent
 */
public class FrmListaDeCitas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmListaDeCitas
     */
    public FrmListaDeCitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaCitas = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        btnPendientes = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnTerminados = new javax.swing.JButton();
        btnCancelados = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(0, 153, 153));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("LISTA DE CITAS");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("CITAS REGISTRADAS EN LA VETERINARIA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        tblListaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListaCitas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 1040, 410));

        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 180, 20));

        btnBuscar.setText("Buscar");
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 90, 30));

        btnTodos.setBackground(new java.awt.Color(0, 153, 153));
        btnTodos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTodos.setForeground(new java.awt.Color(255, 255, 255));
        btnTodos.setText("TODOS");
        jPanel1.add(btnTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 130, 40));

        btnPendientes.setBackground(new java.awt.Color(0, 153, 153));
        btnPendientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPendientes.setForeground(new java.awt.Color(255, 255, 255));
        btnPendientes.setText("PENDIENTES");
        jPanel1.add(btnPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 130, 40));

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("PENDIENTES");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, 40));

        btnTerminados.setBackground(new java.awt.Color(0, 153, 153));
        btnTerminados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTerminados.setForeground(new java.awt.Color(255, 255, 255));
        btnTerminados.setText("TERMINADOS");
        jPanel1.add(btnTerminados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, 40));

        btnCancelados.setBackground(new java.awt.Color(0, 153, 153));
        btnCancelados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelados.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelados.setText("CANCELADOS");
        jPanel1.add(btnCancelados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1203, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCancelados;
    public javax.swing.JButton btnPendientes;
    public javax.swing.JButton btnTerminados;
    public javax.swing.JButton btnTodos;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTable tblListaCitas;
    public javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
